### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by m-noonan** [MatthiasLienhard/isotools#8]
Hello, I'm running IsoTools in command line and keep getting an AssertionError with the TALAM1 gene after sample import. Is this something on my end? Does it have to do with the annotation I'm using? I previously ran IsoTools with just 2 mouse samples and it worked just fine, so I'm not sure if it's something to do with my human genome/reference and/or samples. Any help would be appreciated!

samples='samples.txt'
anno='gencode.v43.annotation.gtf'
genome='GRCh38.primary_assembly.genome.fa'

run_isotools \
     --anno $anno \
     --log INFO \
     --progress_bar \
     --genome $genome \
     --samples $samples \
     --file_prefix ./isotools \
     --group_by group \
     --diff \
     --diff_plots 5 \
     --diff NT/KD

 59%|███████████████████████████████████████████████████▋                                    | 142870/243415 [1:21:17<57:12, 29.29genes/s]2023-06-15 19:14:41 ERROR: Gene TALAM1 chr11:65499311-65507432(-), 1 reference transcripts, 150 expressed transcripts TSS= {'hNT1': {65504026: 1}}, PAS={'hNT1': {65500537: 1}} -> TSS_unified= {'hNT1': {65500848: 1}}, PAS_unified={'hNT1': {65500537: 1}}
 59%|███████████████████████████████████████████████████▋                                    | 142884/243415 [1:21:17<57:11, 29.30genes/s]
Traceback (most recent call last):
  File "/home/data/Megan/anaconda3/bin/run_isotools", line 8, in <module>
    sys.exit(main())
  File "/home/data/Megan/anaconda3/lib/python3.9/site-packages/isotools/run_isotools.py", line 66, in main
    isoseq = load_isoseq(args)
  File "/home/data/Megan/anaconda3/lib/python3.9/site-packages/isotools/run_isotools.py", line 155, in load_isoseq
    isoseq.add_qc_metrics(args.genome, progress_bar=args.progress_bar)
  File "/home/data/Megan/anaconda3/lib/python3.9/site-packages/isotools/_transcriptome_filter.py", line 68, in add_qc_metrics
    g._unify_ends()
  File "/home/data/Megan/anaconda3/lib/python3.9/site-packages/isotools/gene.py", line 897, in _unify_ends
    assert end > tr['exons'][-1][0] or len(tr['exons']) == 1, 'error unifying %s: %s<=%s' % (tr["exons"], end, tr['exons'][-1][0])
AssertionError: error unifying [[65500537, 65500920], [65501008, 65504026]]: 65500848<=65501008

**Comment by MatthiasLienhard** [comment]
This should be fixed now, in 0.3.4. If something is not working, please file a new issue.

**Comment by m-noonan** [comment]
Just wanted to come back and let you know I tried it with the update 0.3.4 and it worked! Thanks for the fix!
